# Generated by Django 2.0.5 on 2019-08-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='facebook',
            field=models.CharField(default='SOME STRING', help_text='title of message.', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='SOME STRING', help_text='title of message.', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.CharField(default='SOME STRING', help_text='title of message.', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='title of message.', max_length=200),
        ),
    ]
