# Generated by Django 2.0.5 on 2019-08-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0002_auto_20190813_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='SOME STRING', help_text='title of message.', max_length=200),
        ),
    ]
