# Generated by Django 2.0.5 on 2019-08-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0003_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.CharField(default='SOME STRING', help_text='title of message.', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='SOME STRING', help_text='title of message.', max_length=200),
        ),
    ]
